# Generated by Django 4.2.5 on 2023-12-16 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('room', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('price', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('1', 'Residential'), ('2', 'Commercial')], default='1', max_length=1)),
                ('furnis', models.CharField(choices=[('1', 'Semi-Furnish'), ('2', 'Fully-Furnish')], default='1', max_length=1)),
                ('stat', models.CharField(choices=[('1', 'Draft'), ('2', 'Available'), ('3', 'Sold')], default='2', max_length=1)),
                ('date', models.DateField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.agent')),
            ],
        ),
    ]
