# Generated by Django 4.2.5 on 2023-12-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image1',
            field=models.ImageField(upload_to='./property/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image2',
            field=models.ImageField(blank=True, upload_to='./property/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image3',
            field=models.ImageField(blank=True, upload_to='./property/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image4',
            field=models.ImageField(blank=True, upload_to='./property/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image5',
            field=models.ImageField(blank=True, upload_to='./property/'),
        ),
    ]
