# Generated by Django 4.2.5 on 2023-12-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_property_image1_alter_property_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bed',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
