# Generated by Django 4.2.5 on 2023-12-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_property_description_alter_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='image',
            field=models.ImageField(default='NA', upload_to='./'),
        ),
    ]
