# Generated by Django 4.2.5 on 2024-03-06 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_agent_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image5',
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='./property/')),
                ('listing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.property')),
            ],
        ),
    ]
